# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


group :development, :test do
end

group :test do
  gem 'selenium-webdriver', '~> 3.142'
  gem 'capybara', '~> 3.31'
  gem 'rspec', '~> 3.9'
end
