# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'grape'
gem 'puma'

group :development, :test do
  gem 'guard-rspec', require: false
end

group :test do
  gem 'rack-test', require: false
  gem 'simplecov', require: false
end
