version: '3.7'

services:
  web:
    container_name: create-react-app_web
    build: .
    image: create-react-app:0.1.0
    ports:
      - 8000:80
    environment:
      - PROXY_API_TARGET=http://jsonplaceholder.typicode.com
